export const CountryActionTypes = {
    FETCH_COUNTRY_START: 'FETCH_COUNTRY_START',
    FETCH_COUNTRY_SUCCESS: 'FETCH_COUNTRY_SUCCESS',
    FETCH_COUNTRY_FAILURE: 'FETCH_COUNTRY_FAILURE',

    UPDATE_COUNTRY_START: 'UPDATE_COUNTRY_START',
    UPDATE_COUNTRY_SUCCESS: 'UPDATE_COUNTRY_SUCCESS',
    UPDATE_COUNTRY_FAILURE: 'UPDATE_COUNTRY_FAILURE',

    UPDATE_COUNTRY_ARRAY: 'UPDATE_COUNTRY_ARRAY',

    FETCH_REGION_START: 'FETCH_REGION_START',
    FETCH_REGION_SUCCESS: 'FETCH_REGION_SUCCESS',
    FETCH_REGION_FAILURE: 'FETCH_REGION_FAILURE',

    UPDATE_SEARCH_FILTER_COUNTRY: 'UPDATE_SEARCH_FILTER_COUNTRY'
}